# workaround for https://github.com/jitpack/jitpack.io/issues/1887

jdk:
  - oraclejdk8
before_install:
  - wget http://central.maven.org/maven2/org/scala-sbt/sbt-launch/1.3.6/sbt-launch-1.3.6.jar
install:
  - SCALAJS_VERSION=0.6.31    java -jar sbt-launch-1.3.6.jar -no-colors +publishM2
  - SCALAJS_VERSION=1.0.0-RC2 java -jar sbt-launch-1.3.6.jar -no-colors +publishM2
